InlayHints:
  Enabled: Yes

---

If:
  # Note: This is a regexp, notice '.*' at the end of PathMatch string.
  PathMatch: [out/.*, build/.*]
Index:
  # Disable slow background indexing of these files.
  Background: Skip
